export const socialMediaWebsites = [
  {name: "facebook.com", enabled: true},
  {name: "twitter.com", enabled: true},
  {name: "x.com", enabled: true},
  {name: "instagram.com", enabled: true},
  {name: "linkedin.com", enabled: true},
  {name: "youtube.com", enabled: true},
  {name: "tiktok.com", enabled: true},
  {name: "pinterest.com", enabled: true},
  {name: "reddit.com", enabled: true},
  {name: "tumblr.com", enabled: true},
  {name: "snapchat.com", enabled: true},
  {name: "whatsapp.com", enabled: true},
  {name: "weibo.com", enabled: true},
  {name: "vk.com", enabled: true},
  {name: "discord.com", enabled: true},
  {name: "twitch.tv", enabled: true},
  {name: "telegram.org", enabled: true},
  {name: "clubhouse.com", enabled: true},
  {name: "medium.com", enabled: true},
  {name: "substack.com", enabled: true},
  {name: "mastodon.social", enabled: true},
  {name: "flickr.com", enabled: true},
  {name: "quora.com", enabled: true},
  {name: "meetup.com", enabled: true},
  {name: "patreon.com", enabled: true},
  {name: "vimeo.com", enabled: true},
]
